name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Congrats!! this is your first issue in this repo😀😀 Happy contributing'
        pr-message: 'Congrats!! this is your first Pull-Request in this repo😀😀 Happy contributing'
